# Malha de Aterramento
## Objetivos

In [21]:
# Passo 1 - Importar base de dados
import pandas as pd

medicao = pd.read_csv('Medição dia 18.csv', index_col=0)

display(medicao)

medicao

,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,P11,P12
P1,NaN,13 mA,NaN,NaN,128 mA,NaN,NaN,NaN,NaN,NaN,NaN,NaN
P2,270 mA,NaN,380 mA,NaN,NaN,706 mA,NaN,NaN,NaN,NaN,NaN,NaN
P3,NaN,325 mA,NaN,227 mA,NaN,NaN,325 mA,NaN,NaN,NaN,NaN,NaN
P4,NaN,NaN,274 mA,NaN,NaN,NaN,NaN,147 mA,NaN,NaN,NaN,NaN
P5,278 mA,NaN,NaN,NaN,NaN,"1,01 A",NaN,NaN,347 mA,NaN,NaN,NaN
P6,NaN,812 mA,NaN,NaN,"1,07 A",NaN,"1,15 A",NaN,NaN,"1,01 A",NaN,NaN
P7,NaN,NaN,283 mA,NaN,NaN,"1,09 A",NaN,389 mA,NaN,NaN,268 mA,NaN
P8,NaN,NaN,NaN,101 mA,NaN,NaN,344 mA,NaN,NaN,NaN,NaN,"85,1 mA"
P9,NaN,NaN,NaN,NaN,289 mA,NaN,NaN,NaN,NaN,238 mA,NaN,NaN
P10,NaN,NaN,NaN,NaN,NaN,954 mA,NaN,NaN,267 mA,NaN,267 mA,NaN
P11,NaN,NaN,NaN,NaN,NaN,NaN,245 mA,NaN,NaN,246 mA,NaN,242 mA
P12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,227 mA,NaN,NaN,227 mA,NaN

In [17]:
# Passo 2 - Tratamento da base de dados

display(medicao)

Index(['P1', 'P2', 'P3', 'P4', 'P5', 'P6', 'P7', 'P8', 'P9', 'P10', 'P11',
       'P12'],
      dtype='object')